// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UTS_Project_ViraNarullita.Models;

#nullable disable

namespace UTS_Project_ViraNarullita.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20250201063056_Add Migration Table Produk and Pesanan")]
    partial class AddMigrationTableProdukandPesanan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("UTS_Project_ViraNarullita.Models.DB.Pesanan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlamatPembeli")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("IdProduk")
                        .HasColumnType("int");

                    b.Property<int>("Jumlah")
                        .HasColumnType("int");

                    b.Property<string>("NamaPembeli")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TanggalPesanan")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Pesanan");
                });

            modelBuilder.Entity("UTS_Project_ViraNarullita.Models.DB.Produk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Harga")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NamaProduk")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TanggalCreate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TanggalKadaluwarsa")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Produk");
                });
#pragma warning restore 612, 618
        }
    }
}
